version = 1

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "jest",
    "vitest",
    "nodejs"
  ]

[[analyzers]]
name = "secrets"

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "isort"

[[code_formatters]]
name = "yapf"

[[code_formatters]]
name = "autopep8"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "ruff"

[[code_formatters]]
name = "rustfmt"